export enum GlobalEnum {
  DATE_FROM = ' 00:00:00',
  DATE_TO = ' 23:59:59',
  PAGE_DEFAULT = 1,
  PAGE_LIMIT = 10,
  COMPANY_TYPE = 1,
  COMPANY_PAGE_SETTING_FLAG = 1,
  MATCHING_SERVICE_CONTRACT_FLAG = 1,
  FLAG = 1,
  STATUS = 2,
}
