import { Seeder } from '@jorgebodega/typeorm-seeding';
import { WorkoutEquipment } from '../../../entities/workout-equipment.entity';
import { DataSource } from 'typeorm';

export default class WorkoutEquipmentSeeder extends Seeder {
  public async run(dataSource: DataSource): Promise<void> {
    const specialWorkoutEquipment = [
      { workout_id: 1, equipment_id: 1 },
      { workout_id: 1, equipment_id: 2 },
      { workout_id: 1, equipment_id: 3 },
      { workout_id: 1, equipment_id: 4 },
      { workout_id: 2, equipment_id: 5 },
      { workout_id: 2, equipment_id: 6 },
      { workout_id: 2, equipment_id: 7 },
      { workout_id: 2, equipment_id: 8 },
      { workout_id: 3, equipment_id: 9 },
      { workout_id: 3, equipment_id: 10 },
      { workout_id: 3, equipment_id: 11 },
      { workout_id: 3, equipment_id: 12 },
      { workout_id: 4, equipment_id: 13 },
      { workout_id: 4, equipment_id: 14 },
      { workout_id: 4, equipment_id: 15 },
      { workout_id: 4, equipment_id: 16 },
      { workout_id: 5, equipment_id: 17 },
      { workout_id: 5, equipment_id: 18 },
      { workout_id: 5, equipment_id: 19 },
      { workout_id: 5, equipment_id: 20 },
      { workout_id: 6, equipment_id: 21 },
      { workout_id: 6, equipment_id: 22 },
      { workout_id: 6, equipment_id: 23 },
      { workout_id: 6, equipment_id: 24 },
      { workout_id: 7, equipment_id: 25 },
      { workout_id: 7, equipment_id: 26 },
      { workout_id: 7, equipment_id: 27 },
      { workout_id: 7, equipment_id: 28 },
      { workout_id: 8, equipment_id: 29 },
      { workout_id: 8, equipment_id: 30 },
      { workout_id: 8, equipment_id: 31 },
      { workout_id: 8, equipment_id: 32 },
      { workout_id: 9, equipment_id: 33 },
      { workout_id: 9, equipment_id: 34 },
      { workout_id: 9, equipment_id: 35 },
      { workout_id: 9, equipment_id: 36 },
      { workout_id: 10, equipment_id: 37 },
      { workout_id: 10, equipment_id: 38 },
      { workout_id: 10, equipment_id: 39 },
      { workout_id: 10, equipment_id: 40 },
      { workout_id: 11, equipment_id: 41 },
      { workout_id: 11, equipment_id: 42 },
      { workout_id: 11, equipment_id: 43 },
      { workout_id: 11, equipment_id: 44 },
      { workout_id: 12, equipment_id: 45 },
      { workout_id: 12, equipment_id: 46 },
      { workout_id: 12, equipment_id: 47 },
      { workout_id: 12, equipment_id: 48 },
      { workout_id: 13, equipment_id: 49 },
      { workout_id: 13, equipment_id: 50 },
      { workout_id: 13, equipment_id: 51 },
      { workout_id: 13, equipment_id: 52 },
      { workout_id: 14, equipment_id: 1 },
      { workout_id: 14, equipment_id: 2 },
      { workout_id: 14, equipment_id: 3 },
      { workout_id: 14, equipment_id: 4 },
      { workout_id: 15, equipment_id: 5 },
      { workout_id: 15, equipment_id: 6 },
      { workout_id: 15, equipment_id: 7 },
      { workout_id: 15, equipment_id: 8 },
      { workout_id: 16, equipment_id: 9 },
      { workout_id: 16, equipment_id: 10 },
      { workout_id: 16, equipment_id: 11 },
      { workout_id: 16, equipment_id: 12 },
      { workout_id: 17, equipment_id: 13 },
      { workout_id: 17, equipment_id: 14 },
      { workout_id: 17, equipment_id: 15 },
      { workout_id: 17, equipment_id: 16 },
      { workout_id: 18, equipment_id: 17 },
      { workout_id: 18, equipment_id: 18 },
      { workout_id: 18, equipment_id: 19 },
      { workout_id: 18, equipment_id: 20 },
      { workout_id: 19, equipment_id: 21 },
      { workout_id: 19, equipment_id: 22 },
      { workout_id: 19, equipment_id: 23 },
      { workout_id: 19, equipment_id: 24 },
      { workout_id: 20, equipment_id: 25 },
      { workout_id: 20, equipment_id: 26 },
      { workout_id: 20, equipment_id: 27 },
      { workout_id: 20, equipment_id: 28 },
      { workout_id: 21, equipment_id: 29 },
      { workout_id: 21, equipment_id: 30 },
      { workout_id: 21, equipment_id: 31 },
      { workout_id: 21, equipment_id: 32 },
      { workout_id: 22, equipment_id: 33 },
      { workout_id: 22, equipment_id: 34 },
      { workout_id: 22, equipment_id: 35 },
      { workout_id: 22, equipment_id: 36 },
      { workout_id: 23, equipment_id: 37 },
      { workout_id: 23, equipment_id: 38 },
      { workout_id: 23, equipment_id: 39 },
      { workout_id: 23, equipment_id: 40 },
      { workout_id: 24, equipment_id: 41 },
      { workout_id: 24, equipment_id: 42 },
      { workout_id: 24, equipment_id: 43 },
      { workout_id: 24, equipment_id: 44 },
      { workout_id: 25, equipment_id: 45 },
      { workout_id: 25, equipment_id: 46 },
      { workout_id: 25, equipment_id: 47 },
      { workout_id: 25, equipment_id: 48 },
    ];

    try {
      await dataSource
        .createEntityManager()
        .save(WorkoutEquipment, specialWorkoutEquipment);
      console.log('Workout equipments seeded successfully');
    } catch (error) {
      console.error(
        'Error occurred while seeding workout equipments',
        error.message,
      );
    }
  }
}
